### ISSUE TITLE
[3pt]  - Display comments for a given item on the Comments pop-up - Student B

### ISSUE THREAD

**Issue by youmari** [youmari/Js-capstone-project#11]
When the popup loads, the webapp retrieves data from the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to show the item comments.

<img width="465" alt="Screenshot 2021-06-27 at 22 21 00" src="https://user-images.githubusercontent.com/7466903/123558341-f8406200-d795-11eb-9074-9a6e2b6a7ec8.png">

This task **does not** include the counter of the comments.

**Comment by KayLemba** [comment]
Hello @youmari 
Can't you see that the ability to add comments is in my next task?

The main object was to ensure that when the code is able to read and display available comments. If you check closely there is a message that reads to info you that the're no comments added yet. Logically that makes sense looking at the code objective of this PR.

**Comment by KayLemba** [comment]
When You approve this PR, giving me a chance to work on the next task, you'll be able to see the comments when they're added. Here We were just expected to fetch the data that is available.
