### ISSUE TITLE
set up Kanban board

### ISSUE THREAD

**Issue by youmari** [youmari/Js-capstone-project#22]
# Set up kanban board
## the link to the repo 
- https://github.com/youmari/Js-capstone-project
###  Note ⚠: in this project, there are two-person @youmari  and @KayLemba

**Comment by ZeenatLawal** [comment]
Hi @youmari and @KayLemba, 

Your Kanban board is good!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
![6vEo](https://user-images.githubusercontent.com/46851023/133564373-95c66227-e33a-4506-b21a-d6db9b3a2050.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
