### ISSUE TITLE
Morning Session:Peer-to-peer Review

### ISSUE THREAD

**Issue by Buyaki01** [youmari/Js-capstone-project#26]
Good work so far :tada::tada:,,,Keep it up!!

**Comment by Tumworobere** [comment]
Everything looks good. Well done @youmari !

**Comment by youmari** [comment]
#### @Buyaki01 @Tumworobere  thank you guys for the feedback 👍

**Comment by youmari** [comment]
#### @Buyaki01 @Tumworobere  thank you guys for the feedback 👍
